chore(refactor): init merge cell service
dream-num/univer pull request #1018
Opened 2024-01-05 09:47 UTC by Gggpound

2024-01-22 07:03 UTC, wzhudev commented on packages/sheets/src/services/merge-cell/merge-cell.service.ts
> +    getCellInfoInfo(unitID: string, subUnitId: string, row: number, col: number): ISelectionCell {
这个 API 名字是啥意思？

2024-01-22 07:04 UTC, Gggpound commented on packages/sheets/src/services/merge-cell/merge-cell.service.ts
> +    getCellInfoInfo(unitID: string, subUnitId: string, row: number, col: number): ISelectionCell {
迁移过来的,会拿到当前单元格的信息（包含合并单元格相关的属性。）

2024-01-22 07:06 UTC, wzhudev requested changes
No context is provided for why this refactor is necessary and what is actually done. Unable to provide review opinions.

2024-01-22 07:06 UTC, wzhudev commented on packages/core/src/sheets/worksheet.ts
>      getMergeData(): IRange[] {
为什么要把这个 API 去掉？

2024-01-22 07:08 UTC, Gggpound commented on packages/core/src/sheets/worksheet.ts
>      getMergeData(): IRange[] {
这个属于 model ，业务使用应该统一归属到 service .

2024-01-22 07:11 UTC, Gggpound commented on packages/core/src/sheets/worksheet.ts
>      getMergeData(): IRange[] {
目前渲染层那边没有接入 di，所以这个 api 没办法完全去掉.

2024-01-22 07:14 UTC, wzhudev commented on packages/core/src/sheets/worksheet.ts
>      getMergeData(): IRange[] {
> 这个属于 model ，业务使用应该统一归属到 service .

为什么获取合并单元格算作所谓的“业务使用”，获取单元格内容不算？

2024-01-22 07:32 UTC, Gggpound commented on packages/core/src/sheets/worksheet.ts
>      getMergeData(): IRange[] {
我觉得拿单元格内容也应该走 service 拦一层的...要弱化 worksheet 这个概念, 本身 worksheet 算 snapshot。 
对外提供 api 又是走的 facade（基于 service 进行的 api 组装）,

2024-01-23 06:58 UTC, Dushusir approved these changes

2024-03-05 12:24 UTC, closed without merging