feat(facade): add set font apis and get cell model data api
dream-num/univer pull request #1266
Opened 2024-01-25 17:13 UTC by hexf00

- [x] I am sure that the code is update-to-date with the `dev` branch.

close #1009

Add Facade APIs:

- getCellData
- getCellStyleData
- setFontStyle
- setFontLine
- setFontFamily
- setFontSize
- setFontColor

2024-02-06 00:29 UTC, wzhudev requested changes
Good work! Though minor changes would be appreciated.

2024-02-06 05:48 UTC, hexf00 commented on packages/facade/src/apis/sheet/f-range.ts
> +export type FontLine = 'none' | 'underline' | 'line-through';
这里是对照 Apps Script 定义的参数，其它地方没有导出

2024-02-06 05:55 UTC, hexf00 commented on packages/facade/src/apis/sheet/f-range.ts
> +        this._commandService.executeCommand(SetStyleCommand.id, setStyleParams);
这里参照AppScripts设计，是链式调用，没有返回调用的状态，保持异步调用会不会更快？

2024-02-06 06:27 UTC, hexf00 commented on packages/facade/src/apis/sheet/__tests__/f-range.spec.ts
> -/* eslint-disable no-magic-numbers */
这个规则应该过期了，去掉没有报错，加上会被lint自动去掉了

2024-02-06 06:41 UTC, hexf00 commented on packages/facade/src/apis/sheet/__tests__/f-range.spec.ts
> +        const activeSheet = univerAPI.getActiveWorkbook()?.getActiveSheet();
已改

2024-02-06 06:51 UTC, wzhudev commented on packages/facade/src/apis/sheet/f-range.ts
> +        this._commandService.executeCommand(SetStyleCommand.id, setStyleParams);
不会，SetStyleCommand 内部实现就是同步的

2024-02-06 06:52 UTC, wzhudev approved these changes

2024-02-06 06:52 UTC, merged

2024-02-07 06:57 UTC, hexf00 commented on packages/facade/src/apis/sheet/f-range.ts
> +        this._commandService.executeCommand(SetStyleCommand.id, setStyleParams);
了解了，后续调整下