refactor(base-ui): change class to function component
dream-num/univer pull request #129
Opened 2023-09-12 02:20 UTC by Dushusir

2023-09-12 02:23 UTC, wzhudev requested changes
组件的 props 和组件的实现要在同一个文件里，`Interface` 这样的目录以后不再有了

2023-09-12 10:33 UTC, Dushusir commented
> 组件的 props 和组件的实现要在同一个文件里，`Interface` 这样的目录以后不再有了

OK。剩下几个业务组件接口，待业务组件从ui-plugin-sheets迁移完后再整理。

2023-09-12 12:56 UTC, jikkai approved these changes
LGTM

2023-09-13 00:24 UTC, wzhudev approved these changes

2023-09-13 01:39 UTC, merged