feat: hide the header menu when there is no content in it
dream-num/univer pull request #1331
Opened 2024-02-03 13:09 UTC by jikkai

- [x] I am sure that the code is update-to-date with the `dev` branch.

2024-02-03 13:35 UTC, Jocs approved these changes

2024-02-04 01:54 UTC, wzhudev requested changes

2024-02-04 01:54 UTC, wzhudev commented on packages/ui/src/views/components/doc-bars/Toolbar.tsx
> +                asdf
Huh huh.

2024-02-06 00:43 UTC, wzhudev approved these changes

2024-02-06 00:43 UTC, merged