fix: cut paste undo bug
dream-num/univer pull request #1353
Opened 2024-02-07 15:37 UTC by yuhongz

- [ ] I am sure that the code is update-to-date with the `dev` branch.

close #

2024-02-08 02:26 UTC, wzhudev commented on packages/sheets-ui/src/controllers/status-bar.controller.ts
> +                        clearTimeout(this._calculateTimeout);
可以在 selectionMoveEnd$ 后面直接 pipe 一个 throttleTime 的 operator

2024-02-08 02:27 UTC, DR-Univer commented
![image](https://github.com/dream-num/univer/assets/68851825/5650667d-8b56-4ac0-8577-50cab02bbee7)
每次点击鼠标会触发3次status bar统计，mouseup又会触发3次统计

2024-02-08 02:49 UTC, wzhudev requested changes
Good work. Some performance issue and code readability issue there.

2024-02-08 02:49 UTC, wzhudev commented on packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
> +            expect(getValues(24, 0, 24, 0)?.[0][0]).toBe(null);
测试用例中使用 `!` 做断言即可，如果有意外的空值情形，抛出错误才是好的

2024-02-08 02:49 UTC, wzhudev commented on packages/sheets-ui/src/services/clipboard/clipboard.service.ts
> +    copyContentCache(): CopyContentCache;
给这个 interface 的方法都加一个注释吧，毕竟是要暴露给用户的接口

2024-02-08 02:49 UTC, wzhudev commented on packages/sheets-ui/src/services/clipboard/clipboard.service.ts
> +        const filteredRows = hooks.reduce((acc, cur) => {
尽量不要删除原先的注释，会影响代码的可理解性

2024-02-08 02:54 UTC, Dushusir approved these changes

2024-02-19 06:52 UTC, wzhudev approved these changes
LGTM

2024-02-19 06:59 UTC, merged