feat(facade): register sheet render extension
dream-num/univer pull request #1356
Opened 2024-02-08 06:26 UTC by Dushusir

- [x] I am sure that the code is update-to-date with the `dev` branch.

close #

add facade apis for sheet render extension
- [x] registerSheetRowHeaderExtension
- [x] unregisterSheetRowHeaderExtension
- [x] registerSheetColumnHeaderExtension
- [x] unregisterSheetColumnHeaderExtension
- [x] registerSheetMainExtension
- [x] unregisterSheetMainExtension

2024-02-08 14:53 UTC, jikkai approved these changes

2024-02-19 05:11 UTC, wzhudev requested changes

2024-02-19 05:11 UTC, wzhudev commented on packages/facade/src/apis/facade.ts
> +        const renderManagerService = injector.get(IRenderManagerService, Quantity.OPTIONAL);
这里为什么要手动去 add 一下？

2024-02-19 05:11 UTC, wzhudev commented on packages/facade/src/apis/facade.ts
> +    unregisterSheetMainExtension(unitId: string, ...uKeys: string[]) {
同上，不一一评论了

2024-03-04 03:58 UTC, wzhudev commented on packages/facade/src/apis/facade.ts
> +        sheetComponent.register(...extensions);
去掉 SheetComponent.unregister 方法吧，register 返回一个 `IDisposable`

2024-03-08 02:55 UTC, wzhudev approved these changes

2024-03-08 02:55 UTC, wzhudev commented on packages/engine-render/src/components/component.ts
>      register(...extensions: Array<ComponentExtension<T, U, V>>) {
增加一个返回类型注释 `IDisposable`

2024-03-08 03:18 UTC, merged