feat(sheet): support ref-range-formula-service & custom-cell-render-extension
dream-num/univer pull request #1564
Opened 2024-03-13 02:29 UTC by weird94

- [ ] I am sure that the code is update-to-date with the `dev` branch.

close #

2024-03-13 06:52 UTC, DR-Univer commented on packages/engine-render/src/components/sheets/extensions/custom.ts
> +                if (!worksheet.getColVisible(col) || !worksheet.getRowVisible(row)) {
贴图渲染缓存要在这里考虑下
![image](https://github.com/dream-num/univer/assets/68851825/9d5ce786-d4ec-4dd3-95ce-a72f88d3bfb8)

2024-03-13 06:52 UTC, DR-Univer commented on packages/sheets-formula/src/services/formula-ref-range.service.ts
> +    registerFormula(formulaId: string, formula: string, callback: FormulaChangeCallback): IDisposable {
update-formula.controller.ts 里的逻辑有做抽象么？这里没有看到，最好是一套逻辑来维护

2024-03-18 04:42 UTC, wzhudev requested changes
JSDoc is not provided. IMHO there should be examples to demonstrate how to use this API.

2024-03-18 04:42 UTC, wzhudev commented on packages/core/src/types/interfaces/i-cell-custom-render.ts
> +export interface ICellRenderContext {
These interface may be not the most appropriate to be placed in package `core`.

2024-03-18 04:42 UTC, wzhudev commented on packages/core/src/types/interfaces/i-cell-data.ts
> +    customRender?: Nullable<ICellCustomRender[]>;
We should provide a similar interceptor on the rendering package instead of making into core.

2024-04-01 11:51 UTC, closed without merging