feat(formula): add the Maxifs function
dream-num/univer pull request #1711
Opened 2024-03-27 09:41 UTC by karlsbeard

* feat: update the i18n file
* feat: add the formula description
* feat: add the formula algorithm
* feat: add the unit test
* feat: complete the function test
* fix: change sumRange to maxRange

2024-03-27 09:58 UTC, Dushusir commented on packages/sheets-formula/src/services/function-list/statistical.ts
> +                name: 'formula.functionList.MAXIFS.functionParameter.sumRange.name',
maxRange

2024-03-27 10:03 UTC, Dushusir approved these changes

2024-03-27 10:05 UTC, Dushusir commented
very good code !

2024-04-08 09:51 UTC, wzhudev requested changes
Overall LGTM. A minor path issue need to be fixed.

2024-04-08 09:51 UTC, wzhudev commented on packages/engine-formula/src/functions/statistical/maxifs/__tests__/index.spec.ts
> +import { Maxifs } from '..';
This import path should be fixed.

2024-04-08 09:51 UTC, wzhudev commented on packages/engine-formula/src/functions/statistical/maxifs/__tests__/index.spec.ts
> +            const maxRange = ArrayValueObject.create(/*ts*/ `{
What does these `/*ts*/` do here?

2024-04-09 04:09 UTC, wzhudev approved these changes
LGTM. Well done.

2024-04-09 04:19 UTC, merged