feat(sheet): defined name
dream-num/univer pull request #1737
Opened 2024-03-29 05:07 UTC by DR-Univer

close #xxx, #yyy, #zzzz

2024-04-01 12:57 UTC, Dushusir commented on packages/engine-formula/src/basics/function.ts
> +    definedName,
DefinedName

2024-04-01 13:01 UTC, Dushusir commented on packages/sheets-ui/src/controllers/selection.controller.ts
> +    private _iniDefinedNameListener() {
_initDxxxxxxx

2024-04-01 13:06 UTC, Dushusir approved these changes

2024-04-03 10:10 UTC, jikkai requested changes

2024-04-03 10:10 UTC, jikkai commented on packages/sheets-ui/src/locale/en-US.ts
> +    definedName: {
Should use kebab-case

2024-04-03 10:18 UTC, jikkai approved these changes

2024-04-03 12:20 UTC, merged