feat(facade): add getMaxColumns and getMaxRows API on FWorksheet
dream-num/univer pull request #1775
Opened 2024-04-02 11:49 UTC by fmwww

2024-04-02 12:12 UTC, jikkai requested changes

2024-04-02 12:12 UTC, jikkai commented on packages/facade/src/apis/sheets/f-worksheet.ts
> +     * @return The maximum width of the sheet
Maybe it's not related to the width or the height?

2024-04-02 12:17 UTC, fmwww commented on packages/facade/src/apis/sheets/f-worksheet.ts
> +     * @return The maximum width of the sheet
我看GoogleSheet那边是这么定义的 [https://developers.google.com/apps-script/reference/spreadsheet/sheet#getmaxcolumns](url)

2024-04-02 12:24 UTC, jikkai commented on packages/facade/src/apis/sheets/f-worksheet.ts
> +     * @return The maximum width of the sheet
This might be an mistake, and insisting on using `width` and `height` could lead to confusion.

2024-04-03 02:47 UTC, hexf00 approved these changes

2024-04-03 03:12 UTC, jikkai approved these changes
LGTM

2024-04-03 03:12 UTC, merged