feat(sheets-hyper-link): add hyper link for sheet
dream-num/univer pull request #2330
Opened 2024-05-27 12:57 UTC by weird94

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-05-28 01:55 UTC, wzhudev requested changes
I added a custom eslint so you can catch all importing problems.

2024-05-28 06:45 UTC, weird94 commented on packages/sheets-ui/src/services/hover-manager.service.ts
> +    currentCellDebounce$ = this.currentCell$.pipe(debounceTime(100));
fixed

2024-05-28 07:13 UTC, wzhudev requested changes
After some internal discussion, the implementation of the ref range service need to be updated.

2024-05-29 03:36 UTC, weird94 commented
https://github.com/dream-num/univer/pull/2330#issuecomment-2133491107

2024-05-31 02:58 UTC, weird94 commented
> ## View Deployment
> 📑 Examples	📚 Storybook
> [🔗 Preview link](https://univer-ok0phblmw-univer.vercel.app/)	[🔗 Preview link](https://univer-design-k5c65v9xd-univer.vercel.app/)

pkg

2024-05-31 02:59 UTC, weird94 commented
https://github.com/dream-num/univer/pull/2330#issuecomment-2133491107

2024-05-31 09:31 UTC, wzhudev approved these changes
LGTM

2024-05-31 09:40 UTC, merged