feat: Automatically adjusts the line height when the text wrap button is clicked[WIP]
dream-num/univer pull request #308
Opened 2023-10-21 11:52 UTC by Jocs

- [x] Calculation of row height
- [ ] Auto Height command/mutation

2023-10-21 12:55 UTC, DR-Univer commented on packages/base-sheets/src/commands/commands/set-worksheet-row-height.command.ts
> +        const rowsAutoHeightInfo = skeleton.calculateAutoHeightInRange(selections);
command是纯数据计算，只依赖model，不要依赖view相关的方法和service，可以把相关计算做成一个autoHeight.controller，执行view相关的业务逻辑计算，再调用command执行

2023-10-21 15:24 UTC, Jocs commented on packages/base-sheets/src/commands/commands/set-worksheet-row-height.command.ts
> +        const rowsAutoHeightInfo = skeleton.calculateAutoHeightInRange(selections);
好的👌🏻。

2023-10-23 15:23 UTC, wzhudev requested changes

2023-10-23 15:23 UTC, wzhudev commented on packages/base-render/src/Basics/Tools.ts
> + * Determines whether the cell（row, column） is within the range of the merged cells.
这里用的是中文的括号

2023-10-24 02:12 UTC, Jocs commented on packages/base-render/src/Component/Sheets/SheetSkeleton.ts
> +    autoHeight?: number;
好像没啥区别，本来 autoHeight 是要落库的？

2023-10-24 02:13 UTC, Jocs commented on packages/base-render/src/Component/Sheets/SheetSkeleton.ts
> +    rowNumber: number;
OK。

2023-10-24 02:14 UTC, Jocs commented on packages/base-render/src/Component/Sheets/SheetSkeleton.ts
> +    calculateRowAutoHeight(rowNum: number): number {
+1

2023-10-24 02:17 UTC, Jocs commented on packages/base-render/src/Component/Sheets/SheetSkeleton.ts
> +            for (let i = startRow; i <= endRow; i++) {
+1

2023-10-24 03:15 UTC, wzhudev approved these changes

2023-10-24 03:18 UTC, merged