feat(sheet): insert range handle row/column,merge
dream-num/univer pull request #309
Opened 2023-10-21 12:25 UTC by Dushusir

2023-10-23 15:15 UTC, wzhudev requested changes

2023-10-23 15:15 UTC, wzhudev commented on packages/base-sheets/src/services/selection-manager.service.ts
> +        const rangeList = selectionDataList.map((selectionData: ISelectionWithStyle) => {
这段 map 的逻辑应该抽成一个单独的函数，放到 range 的文件里面去

2023-10-23 15:15 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/utils/selection-util.ts
> +
JSDoc 的位置写错了吧

2023-10-23 15:15 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/insert-range-move-down.command.ts
> +            logService.error('Cannot use that command on overlapping selections.');
这里不只是记录错误日志，应该也要弹窗之类吧

2023-10-24 01:55 UTC, Dushusir commented on packages/base-sheets/src/commands/commands/insert-range-move-down.command.ts
> +            logService.error('Cannot use that command on overlapping selections.');
已加TODO

2023-10-24 02:22 UTC, Dushusir commented on packages/base-sheets/src/services/selection-manager.service.ts
> +        const rangeList = selectionDataList.map((selectionData: ISelectionWithStyle) => {
发现getSelections数组中每个selection的range就可以直接用了，可以省去一次循环

2023-10-24 02:30 UTC, wzhudev approved these changes

2023-10-24 03:11 UTC, merged