feat(docs-ui): limit list maxLevel to 3 when in table
dream-num/univer pull request #3096
Opened 2024-08-16 11:11 UTC by weird94

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-08-16 11:56 UTC, wzhudev requested changes
It is recommended to use a correct syntax.

2024-08-16 11:56 UTC, wzhudev commented on packages/docs/src/basics/paragraph.ts
> +export function isParagraphInTable(paragraph: IParagraph, tables: ICustomTable[]) {
```suggestion
export function hasParagraphInTable(paragraph: IParagraph, tables: ICustomTable[]) {
```

2024-08-16 11:56 UTC, wzhudev commented on packages/docs/src/basics/paragraph.ts
> +export function isParagraphInTable(paragraph: IParagraph, tables: ICustomTable[]) {
`isXXX` is usually considered as a property  or an variable instead of a function.

2024-08-17 03:02 UTC, oumomomo commented
使用多级列表后需要删除两次才可以成功删除单元格内的换行符
操作步骤：
1、新增表格，在单元格内输入字符（需要在单元格内留出一个字符的空间）
![image](https://github.com/user-attachments/assets/7deded43-d5dd-454c-81cd-0ef688ce4978)
2、使用多级列表直到单元格内会展示换行符
3、删除换行符
![image](https://github.com/user-attachments/assets/bd9e0477-29d2-4ac4-820c-e2900686f2b6)


实际表现：需要删除两次才可以删除换行符

2024-08-17 03:10 UTC, oumomomo commented
在单元格内不停增加多级列表会失焦，失焦后选中内容删除表格白屏

1、在单元格输入内容使用多级列表直到失焦
2、选中的单元格内容删除（第一次无反应可以多按两次删除键）
[2024_8_17 11_08_47 video.webm](https://github.com/user-attachments/assets/2ea598b2-bef8-4344-aa14-816c45c1866e)
![image](https://github.com/user-attachments/assets/28634355-630d-4d45-9003-7211f2e5ec31)

2024-08-17 03:35 UTC, oumomomo commented
在单元格内使用第三个有序列表时会失焦

操作步骤：
1、插入表格并在单元格输入内容
2、使用有序列表内的第三个
3、选中内容不停增加子列表
![image](https://github.com/user-attachments/assets/af21b0be-19f8-415d-88d6-707b492e34bc)
[2024_8_17 11_34_23 video.webm](https://github.com/user-attachments/assets/fa69e922-0059-469b-8652-7c15dc777856)

2024-08-22 06:38 UTC, wzhudev approved these changes
LGTM

2024-08-22 06:46 UTC, merged