fix(sheets-data-validation): date validator error when STOP was set
dream-num/univer pull request #3102
Opened 2024-08-17 06:12 UTC by weird94

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-08-17 06:19 UTC, wzhudev requested changes

2024-08-17 06:19 UTC, wzhudev commented on packages/data-validation/src/models/data-validation-model.ts
> +    validator(rule: T, pos: any, value: any) {
Same here.

2024-08-19 06:04 UTC, weird94 commented on packages/data-validation/src/models/data-validation-manager.ts
> +    validator(_value: any, _rule: IDataValidationRule, _pos: any, _onComplete: (status: DataValidationStatus, changed: boolean) => void) {
fixed

2024-08-19 06:04 UTC, weird94 commented on packages/data-validation/src/models/data-validation-model.ts
> +    validator(rule: T, pos: any, value: any) {
fixed

2024-08-19 06:09 UTC, wzhudev approved these changes
LGTM

2024-08-19 07:19 UTC, merged