fix: ref selection expand after bottom line is over top line
dream-num/univer pull request #3104
Opened 2024-08-17 09:31 UTC by lumixraku

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-08-19 06:06 UTC, wzhudev requested changes
There are code quality issues need to be addressed:

1. Do not write implementation details in JSDoc. I've explained the reasons in a comment below.
2. Pay attention to usages of capital letters, punctuations and JSDoc syntax, as the comments you write will be in the API references.
3. Remove dead code, not comment them out.

2024-08-19 06:06 UTC, wzhudev commented on packages/sheets-formula/src/controllers/prompt.controller.ts
> +            // theme color should be set when selection coltrol is created, it's too late to set theme color at selecitonEnd(pointerup).
Spells propblem.

2024-08-19 06:06 UTC, wzhudev commented on packages/sheets-formula/src/controllers/prompt.controller.ts
> +     * refSelectionsRenderService@_pointerDown --> refSelectionsRenderService@_selectionMoveStart$ --> _syncToEditor
Same problem.

2024-08-19 06:06 UTC, wzhudev commented on packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
> +        // this._pointerDown --> this._selectionMoveStart$.next(this.getSelectionDataWithStyle());
Same here.

2024-08-19 06:06 UTC, wzhudev commented on packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
> +            // change sheet ---> currentSkeleton$ change
Same.

2024-08-19 07:44 UTC, lumixraku commented on packages/core/src/sheets/worksheet.ts
> +     * ex: cf.render.controller@_initViewModelInterceptor
never comment where the API is called in JSDoc comments.  -->  The "ex: xxxx" in this comments?

2024-08-19 08:05 UTC, lumixraku commented on packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
> +        // this._pointerDown --> this._selectionMoveStart$.next(this.getSelectionDataWithStyle());
But this is not a JSDoc.

2024-08-23 02:41 UTC, wzhudev approved these changes
LGTM

2024-08-23 02:41 UTC, wzhudev commented on packages/sheets-ui/src/services/selection/selection-render-model.ts
> +     * TODO @lumixraku there are 3 concepts for same thing, primary and current and highlight, primary is better cuz selectionModel is using primary.
TODO 不写在 JSDoc 里面，放外面用 // 注释

2024-08-23 02:48 UTC, merged