feat(sheets-ui): support delete cell on backspace
dream-num/univer pull request #3119
Opened 2024-08-20 02:14 UTC by weird94

close https://github.com/dream-num/univer-pro/issues/1724

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-08-21 01:54 UTC, wzhudev commented
@hexf00 The bot failed to tag `qa:unverified`.

2024-08-21 01:58 UTC, wzhudev requested changes
User behavior is not correct for Windows users.

2024-08-21 01:58 UTC, wzhudev commented on packages/sheets-ui/src/controllers/shortcuts/value.shortcut.ts
> +    binding: KeyCode.BACKSPACE,
In Excel, this behavior should be "start editing with an empty cell editor". The `ClearSelectionContentCommand` is carried by `KeyCode.DELETE`, and already implemented in the lines above.

2024-08-22 12:16 UTC, hexf00 commented
> @hexf00 The bot failed to tag `qa:unverified`.

Automatically add the `qa:untested` label if the PR title starts with `fix:`.

2024-08-23 06:11 UTC, wzhudev approved these changes

2024-08-23 06:11 UTC, wzhudev commented on packages/sheets-thread-comment/src/controllers/sheets-thread-comment.controller.ts
> +                -1
This selection should be marked as `evented: false` instead.

2024-08-23 06:21 UTC, merged