feat(docs-hyper-link): hyper link refactor
dream-num/univer pull request #3148
Opened 2024-08-22 03:44 UTC by weird94

close https://github.com/dream-num/univer-pro/issues/2156

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-08-22 08:43 UTC, oumomomo commented
对.设置超链接，展示tips时无法点击按钮
![image](https://github.com/user-attachments/assets/deaa3e1b-3e07-47e5-a57e-a09c3728ad03)

2024-08-22 09:06 UTC, oumomomo commented
页眉内输入内容设置超链接勾选首页不同，点击第二页的编辑不展示面板
[2024_8_22 17_04_24 video.webm](https://github.com/user-attachments/assets/d76d9a70-dae3-4784-950d-41b3485315fd)

2024-08-23 06:44 UTC, wzhudev requested changes
This PR seems introducing a huge break change into the doc system. I would like to know the following before continue reviewing the code.

* What's the plan to deal with the legacy resources in old snapshots? Will they are lost?
* What users have to change in their code? Are there any breaking changes not documented in the commit messages?

2024-08-23 06:44 UTC, wzhudev commented on packages/core/src/services/command/command.service.ts
> +            { params }
Do not expose params.

2024-08-23 06:44 UTC, wzhudev commented on packages/core/src/types/interfaces/i-document-data.ts
> +    properties?: T;
JSDoc required.

2024-08-23 07:12 UTC, weird94 commented
> This PR seems introducing a huge break change into the doc system. I would like to know the following before continue reviewing the code.
> 
> * What's the plan to deal with the legacy resources in old snapshots? Will they are lost?
> * What users have to change in their code? Are there any breaking changes not documented in the commit messages?
> 
> And this PR's title seems no accurate as not only the hyper link feature was refactored.

1. this change is compatible with the old snapshot, `DocHyperLinkResourceController` will load links from snapshot and sync to custom-ranges.

2024-08-30 03:26 UTC, wzhudev approved these changes
LGTM

2024-09-02 07:10 UTC, merged