feat(sheet): auto height in row context menu
dream-num/univer pull request #323
Opened 2023-10-25 03:49 UTC by Jocs

- [ ] After adjusting the row height, set `isAutoHeight` to `false`
- [ ] Add SetRowAutoHeightCommand
- [ ] When calculating the automatic row height, determine whether the row `isAutoHeight` is `true`

2023-10-25 14:45 UTC, wzhudev requested changes
Some minor issues need to be addressed.

2023-10-25 14:45 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/__tests__/set-row-height.command.spec.ts
> +import { SetWorksheetRowHeightMutation, SetWorksheetRowIsAutoHeightMutation } from '../../..';
注意这里的引用路径

2023-10-25 14:45 UTC, wzhudev commented on packages/ui-plugin-sheets/src/controller/menu/menu.ts
> +import { SetRowIsAutoHeightCommand } from '@univerjs/base-sheets/commands/commands/set-worksheet-row-height.command.js';
注意引用路径问题

这里要不写一下 eslint 规则，禁止在引入 univerjs 出现穿透子路径的行为

2023-10-26 02:09 UTC, Jocs commented on packages/ui-plugin-sheets/src/controller/menu/menu.ts
> +import { SetRowIsAutoHeightCommand } from '@univerjs/base-sheets/commands/commands/set-worksheet-row-height.command.js';
OK

2023-10-26 02:09 UTC, Jocs commented on packages/base-sheets/src/commands/commands/__tests__/set-row-height.command.spec.ts
> +import { SetWorksheetRowHeightMutation, SetWorksheetRowIsAutoHeightMutation } from '../../..';
OK

2023-10-26 02:27 UTC, Jocs commented on packages/ui-plugin-sheets/src/controller/menu/menu.ts
> +import { SetRowIsAutoHeightCommand } from '@univerjs/base-sheets/commands/commands/set-worksheet-row-height.command.js';
后面需要加一下规则，毕竟后面我们要分包发布？

2023-10-26 03:24 UTC, wzhudev approved these changes

2023-10-26 03:32 UTC, merged