feat(sheet): support selection move
dream-num/univer pull request #328
Opened 2023-10-26 08:54 UTC by Gggpound

[ ] 合并单元格
[ ] border样式
[ ] 公式
[ ] 行高列宽

2023-10-30 03:42 UTC, wzhudev requested changes

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +                    const selectionControls = this._selectionRenderService.getCurrentControls();
这里或许可以用 RxJS 里面的 swtichMap 来简化一下写法

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +const getRelativeRange = (range: IRange, originRange: IRange) =>
这里的工具函数可以放到跟 IRange 接口同一个文件中

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +            this._commandService.onCommandExecuted((_params) => {
如果参数会被用到，无需以 `_` 开头

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +            const handler = (config: EffectParams) => {
这里的意图是在移动行列发生的时候对合并单元格做调整？如果是的话似乎没有必要通过反转的方式去弄，直接在 command 里做修改即可，因为属于同一个 plugin 的业务逻辑

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/add-worksheet-merge.command.ts
> +export const getAddMergeMutationRange = (selection: IRange[], type?: Dimension) => {
这个函数的意图很难一眼看出来

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/services/ref-range.service.ts
> +    get worksheetId() {
`worksheetId` 和 `workbookId` 属性不适宜从 `RefRangeService` 暴露

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/services/ref-range.service.ts
> +    private _getRefRangId = (workbookId: string, worksheetId: string) => `${workbookId}_${worksheetId}`;
抽象成一个 function，不要作为类的 method

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/services/ref-range.service.ts
> +    private _serializeRange = (range: IRange) =>
同上

2023-10-30 03:42 UTC, wzhudev commented on packages/base-sheets/src/services/ref-range.service.ts
> +    private _deserialize = (rangeString: string) => {
同上

2023-10-30 08:49 UTC, Gggpound commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +                    const selectionControls = this._selectionRenderService.getCurrentControls();
不太理解，有伪代码吗？

2023-10-30 08:50 UTC, Gggpound commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +const getRelativeRange = (range: IRange, originRange: IRange) =>
好的。

2023-10-30 08:51 UTC, Gggpound commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +            this._commandService.onCommandExecuted((_params) => {
这里开的代码迁移到merge-cell-controller中了,对应的修改，我这边改一下

2023-10-30 08:54 UTC, Gggpound commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +            const handler = (config: EffectParams) => {
不是，应该是所有合并单元格的修改，都统一到一个地方。
这里的意思是，行列的增删/选区移动，都会导致合并单元格的改动。
这里可以把相关的逻辑都集中到merge-cell-controller中处理，不需要分散放到 insert-row-mutation / delete-row-mutation/move-range-mutation 中去执行

2023-10-30 08:57 UTC, Gggpound commented on packages/base-sheets/src/commands/commands/add-worksheet-merge.command.ts
> +export const getAddMergeMutationRange = (selection: IRange[], type?: Dimension) => {
属于合并单元格的具体业务了，这里做了一下抽离。

2023-10-31 06:35 UTC, wzhudev commented on packages/base-sheets/src/Controller/move-range.controller.ts
> +                    const selectionControls = this._selectionRenderService.getCurrentControls();
看一下 RxJS 的文档？

2023-10-31 06:43 UTC, wzhudev requested changes

2023-10-31 06:43 UTC, wzhudev commented on packages/base-sheets/src/Controller/merge-cell.controller.ts
> +            const handler = (config: EffectParams) => {
这个方法这么长，拆解一下；写在一起可维护性还不如之前的

2023-10-31 11:53 UTC, Gggpound commented on packages/base-sheets/src/Controller/merge-cell.controller.ts
> +            const handler = (config: EffectParams) => {
done

2023-10-31 11:53 UTC, Gggpound commented on packages/base-sheets/src/services/ref-range.service.ts
> +    private _getRefRangId = (workbookId: string, worksheetId: string) => `${workbookId}_${worksheetId}`;
done

2023-10-31 12:31 UTC, wzhudev commented on packages/core/src/Shared/lifecycle.ts
> +    disposeWithMe(disposable: IDisposable): IDisposable {
这里为什么要去掉 protected?

2023-10-31 12:32 UTC, wzhudev commented on packages/base-sheets/src/services/ref-range.service.ts
> +    constructor(
注意空行

2023-10-31 12:34 UTC, Gggpound commented on packages/core/src/Shared/lifecycle.ts
> +    disposeWithMe(disposable: IDisposable): IDisposable {
想在外部用 dispose 方法。 这种情况是不是 DisposableCollection 更合适？

2023-10-31 12:35 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
> -            selectRow(2, 2);
为什么会改到测试用例？

2023-10-31 12:36 UTC, wzhudev commented on packages/base-sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
> -            selectRow(2, 2);
你在 test bed 里有增加 MergedCellController 吗？

2023-10-31 12:50 UTC, Gggpound commented on packages/base-sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
> -            selectRow(2, 2);
有增加 MergedCellController 的，在test中实例化 MergedCellController ，就会影响原先编写好的测试用例。

2023-10-31 12:53 UTC, Gggpound commented on packages/base-sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
> -            selectRow(2, 2);
目前的覆盖率
<img width="782" alt="image" src="https://github.com/dream-num/univer/assets/141617023/4d451cf1-55bc-43e4-a288-d610764f5b1b">

2023-11-01 02:25 UTC, wzhudev commented on packages/core/src/Shared/lifecycle.ts
> +    disposeWithMe(disposable: IDisposable): IDisposable {
是的

2023-11-01 03:10 UTC, wzhudev approved these changes

2023-11-01 06:31 UTC, merged