feat(base):auth serivce
dream-num/univer pull request #359
Opened 2023-11-01 06:48 UTC by Gggpound

2023-11-02 02:30 UTC, Jocs commented
进行中的 PR，标记成 Draft 状态吧

2023-11-02 14:01 UTC, wzhudev requested changes

2023-11-02 14:01 UTC, wzhudev commented on packages/core/src/Shared/permission/index.ts
> +const PermissionIdLength = 15;
A blank line before this line.

2023-11-02 14:01 UTC, wzhudev commented on packages/core/src/Shared/permission/index.ts
> +    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
已经有了 nanoid，不需要自己写一个随机数算法吧

2023-11-03 08:11 UTC, Gggpound commented on packages/core/src/services/sheet-interceptor/sheet-interceptor.service.ts
> +     * this function maybe have side effects !!!
a pop/alter/dialog may appear when it fails

2023-11-03 08:26 UTC, Gggpound commented on packages/ui-plugin-sheets/src/controller/menu/menu.ts
> +                permission$ && permission$.unsubscribe();
i think it doesn't matter = =

2023-11-03 08:36 UTC, DR-Univer commented on packages/ui-plugin-sheets/src/controller/menu/menu.ts
> +                permission$ && permission$.unsubscribe();
We need to maintain formation consistency.

2023-11-06 00:49 UTC, wzhudev requested changes
1. PermissionService 和 UniverPermissionService 的职责区别是什么？
2. 可以在 debug plugin 里增加一个设置权限的功能入口方便随时切换权限效果

2023-11-06 00:49 UTC, wzhudev commented on packages/core/src/services/permission/permissionEnum.ts
> +import { PermissionPoint } from '../../Shared/permission';
文件命名使用短横线

2023-11-06 00:49 UTC, wzhudev commented on packages/core/src/services/permission/univer.permission.service.ts
> +        const permission = this._permissionService.getPermissionItem(univerEditablePermission.id);
permissionItem 和 permissionPoint 是两个不同的概念吗？如果是的话分别是什么意思？

2023-11-06 00:49 UTC, wzhudev commented on packages/core/src/services/sheet-interceptor/sheet-interceptor.service.ts
> +     * This function maybe have side effects !!!
如果有 side effect 要说明是什么样的 side effects，不然这段注释没啥效果

2023-11-06 00:49 UTC, wzhudev commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +    getEditable$ = (workbookId?: string, sheetId?: string) => {
不要用赋值的方式指定函数，会有绑定在对象实例和 prototype 上的微妙差别

2023-11-06 00:49 UTC, wzhudev commented on packages/core/src/Shared/permission/index.ts
> +    FETCH = 'fetch',
`FETCHING`

2023-11-06 03:24 UTC, Gggpound commented on packages/core/src/services/permission/univer.permission.service.ts
> +        const permission = this._permissionService.getPermissionItem(univerEditablePermission.id);
一个概念，应该都用point的

2023-11-06 03:25 UTC, Gggpound commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +    getEditable$ = (workbookId?: string, sheetId?: string) => {
这里主要是会给外部用，想把 this 问题处理了

2023-11-06 03:27 UTC, Gggpound commented
> 1. PermissionService 和 UniverPermissionService 的职责区别是什么？
> 2. 可以在 debug plugin 里增加一个设置权限的功能入口方便随时切换权限效果

1. PermissionService 负责权限点位的管理(业务不相关)。 UniverPermissionService 负责具体权限点位干什么（具体的业务。）
2. 这个可以。

2023-11-08 05:22 UTC, wzhudev reviewed
有文档来描述一下所谓权限点的设计吗？最好写在代码里

2023-11-08 05:22 UTC, wzhudev commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +        this.interceptCommandPermission();
私有函数的命名风格应该保持一致

2023-11-08 05:22 UTC, wzhudev commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +        const workbook = this._univerInstanceService.getCurrentUniverSheetInstance();
对于后续创建的 Workbook 和 Worksheet 的处理似乎没有包含在内

2023-11-08 05:22 UTC, wzhudev commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +    getSheetEditable(workbookId?: string, sheetId?: string) {
SheetEditable 和 Editable$ 除了类型上的区别，语义上是否存在区别？

2023-11-08 05:22 UTC, wzhudev commented on packages/core/src/Shared/permission/index.ts
> +export abstract class PermissionPoint<T = any> {
权限点位的数据没有一个基础的类型或者限制？

2023-11-08 05:22 UTC, wzhudev commented on packages/core/src/services/permission/permission.service.ts
> +        const valueList = permissionIdList.map((id) => {
如果调用这个方法之后 permissionItemMap 发生了变化，这里的权限信息就不对了

2023-11-08 05:25 UTC, wzhudev commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +    getSheetEditable(workbookId?: string, sheetId?: string) {
sheetID 是为了处理保护子表？那后续涉及到保护范围的时候是否需要再次修改方法签名？

2023-11-08 06:37 UTC, Gggpound commented on packages/base-sheets/src/services/permission/sheet-permission.service.ts
> +    getSheetEditable(workbookId?: string, sheetId?: string) {
嗯，range 保护是其他权限点位，这里的 editable 主要是出一个示例

2023-11-08 06:42 UTC, Gggpound commented on packages/core/src/Shared/permission/index.ts
> +export abstract class PermissionPoint<T = any> {
没有限制的.不通权限点位的值是不一样的。 editable 只是最简单的布尔值。但是像保护行列，则可能是一个 userid 的列表.(这里的权限判断逻辑，需要前后端同构)

2023-11-08 06:45 UTC, Gggpound commented on packages/core/src/services/permission/permission.service.ts
> +        const valueList = permissionIdList.map((id) => {
你这里说的变化是指的某个permissionPoint被删除了?然后依赖这个进行派发的组合权限会失效？

2023-11-09 07:28 UTC, Gggpound commented on packages/core/src/services/permission/permission.service.ts
> +        const valueList = permissionIdList.map((id) => {
这里直接抛错误了

2023-11-10 03:03 UTC, wzhudev approved these changes

2023-11-10 03:03 UTC, merged