[WIP]feat: auto fill by drag
dream-num/univer pull request #369
Opened 2023-11-02 03:26 UTC by yuhongz

2023-11-03 15:13 UTC, Jocs commented on packages/base-sheets/src/commands/commands/auto-fill.command.ts
> +                        startRow: selectionRange.startRow,
感觉可以解构一下

2023-11-08 05:32 UTC, wzhudev requested changes
需要撰写测试，特别是下拉填充策略的那部分代码

Bugs:

1. 退出下拉填充后，悬浮菜单没有隐藏

2023-11-08 05:32 UTC, wzhudev commented on packages/ui-plugin-sheets/src/commands/commands/auto-fill.command.ts
> +        commandService.executeCommand(SetRangeValuesCommand.id, {
这里分为两个 command 来执行，那么如果要撤销的话是不是也要按两次 command + Z?

2023-11-08 05:32 UTC, wzhudev commented on packages/ui-plugin-sheets/src/controllers/auto-fill.controller.ts
> +        let a1;
来个类型注释

2023-11-08 06:51 UTC, yuhongz commented
> 需要撰写测试，特别是下拉填充策略的那部分代码
> 
> Bugs:
> 
> 1. 退出下拉填充后，悬浮菜单没有隐藏

这里参考 excel，在进入输入态/下一次下拉之前，菜单是一直悬浮着的。

2023-11-08 13:25 UTC, wzhudev commented
> > 需要撰写测试，特别是下拉填充策略的那部分代码
> > Bugs:
> > 
> > 1. 退出下拉填充后，悬浮菜单没有隐藏
> 
> 这里参考 excel，在进入输入态/下一次下拉之前，菜单是一直悬浮着的。

excel 切换选区的时候菜单就会消失哦

2023-11-09 03:18 UTC, wzhudev approved these changes

2023-11-09 04:57 UTC, merged