feat: watermark
dream-num/univer pull request #3751
Opened 2024-10-14 13:23 UTC by ybzky

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-10-19 07:02 UTC, wzhudev requested changes
README of this plugin is empty.

2024-10-19 07:02 UTC, wzhudev commented on packages/watermark/src/commands/operations/OpenWatermarkPanelOperation.ts
> +export const OpenWatermarkPanelOperation: ICommand = {
Name of this file does not follow our naming convension.

2024-10-19 07:02 UTC, wzhudev commented on packages/watermark/src/services/watermarkService.ts
> +export class UniverWatermarkService extends Disposable {
Naming convension.

2024-10-19 08:25 UTC, ybzky commented on packages/sheets-ui/src/services/sheets-render.service.ts
> +                renderer.engine.getCanvas().getContext().setId(SHEET_MAIN_CANVAS_ID);
here only set id to the main canvas

2024-10-22 03:18 UTC, wzhudev approved these changes
LGTM. An e2e visual comparison test would be better.

2024-10-22 03:18 UTC, wzhudev commented on packages/watermark/src/services/watermark.service.ts
> +    private _updateConfig$ = new Subject<Nullable<IWatermarkConfigWithType>>();
```suggestion
    private readonly _updateConfig$ = new Subject<Nullable<IWatermarkConfigWithType>>();
```

2024-10-22 03:18 UTC, wzhudev commented on packages/watermark/src/services/watermark.service.ts
> +    private _updateConfig$ = new Subject<Nullable<IWatermarkConfigWithType>>();
And these observables should `complete` on disposing.

2024-10-22 06:30 UTC, merged