feat(formula): formula prompt component,controller,service,command
dream-num/univer pull request #376
Opened 2023-11-02 13:08 UTC by Dushusir

2023-11-03 03:30 UTC, jikkai commented on examples/univer-sheet-ts/package.json
> +        "@univerjs/sheets-plugin-formula": "workspace:^",
`workspace:*`

2023-11-04 11:03 UTC, jikkai commented on packages/sheets-plugin-formula/src/views/prompt/help-function/index.module.less
> +.formula {
可能需要再斟酌一下 classname，在插件里使用单个单词还是会有一些重名风险

2023-11-04 11:04 UTC, jikkai commented on packages/sheets-plugin-formula/src/views/prompt/search-function/index.module.less
> +.formula {
重名风险出现 :trollface:

2023-11-04 11:05 UTC, jikkai commented on packages/sheets-plugin-formula/tsconfig.json
> +        "test/**/*.test.(ts|tsx|js)"
All test files are located in the `src` directory, so this line may be unnecessary.

2023-11-06 00:55 UTC, wzhudev requested changes
另外 PR description 里要附上对修改内容的简短描述

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/editor-formula.operation.ts
> +// This file provide operations to change selection of sheets.
```suggestion
// This file provides operations to change formula selection of sheets.
```

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/editor-formula.operation.ts
> +export const SetEditorFormulaArrowOperation: IOperation<ISetEditorFormulaArrowOperationParam> = {
什么叫做设置公式箭头？

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/editor-formula.operation.ts
> +export const SetEditorFormulaArrowOperation: IOperation<ISetEditorFormulaArrowOperationParam> = {
这个名字是否可以再考虑考虑？

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/editor-formula.operation.ts
> +                formulaPromptService.setNavigate({ direction: Direction.DOWN });
这个 API 就叫 `navigate` 即可，`setNavigate` 看起来像是改了内部的一个 flag，但应该只是切换上下选项而已

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/help-function.operation.ts
> +    show: boolean;
show 是动词，换成 visible

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/commands/operations/help-function.operation.ts
> +        promptService.setHelp(params.show);
setHelp 名字换一下

2023-11-06 00:55 UTC, wzhudev commented on packages/sheets-plugin-formula/src/controllers/formula.controller.ts
> +        this.registerShortcuts();
这个方法的命名和其他三个不一致

2023-11-06 00:55 UTC, wzhudev commented
Rebase 一下好了，很多样式都挂了

2023-11-06 07:17 UTC, Dushusir commented
> Rebase 一下好了，很多样式都挂了

ok

2023-11-08 08:15 UTC, wzhudev approved these changes

2023-11-08 08:19 UTC, merged