refactor(permission-ui): refactor permission-ui & user part can be customized
dream-num/univer pull request #3945
Opened 2024-11-04 08:29 UTC by ybzky

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-11-05 02:36 UTC, Gggpound approved these changes

2024-11-06 00:45 UTC, wzhudev requested changes
A few questions:

* How can users custom the users' list panel? If there a tutorial or something?
* There are two different commands with the same name `AddRangeProtectionCommand` and why?
* Can Node.js SDK users change permissions?

2024-11-06 00:45 UTC, wzhudev commented on packages/core/src/services/command/command.service.ts
> +                this._logService.error(error);
Wouldn't the error get logged twice here?

2024-11-06 00:45 UTC, wzhudev commented on packages/sheets-ui/src/commands/commands/worksheet-protection.command.ts
> +    oldRule: IWorksheetProtectionRule;
Should have some JSDoc on command params.

2024-11-06 00:51 UTC, wzhudev commented
And I have to say that the demo on preview site looks really like a bug after you set some permissions and they do not appears in the sidebar.

2024-11-07 07:54 UTC, ybzky commented
1. node supports setting permissions but has not started to be modified
2. the legacy code has been deleted
3. currently all changes to the panel are packaged in the univer-pro for QA verification because they involve request-related logic

2024-11-08 06:53 UTC, wzhudev approved these changes

2024-11-08 06:54 UTC, merged