fix: fix numfmt without plugin
dream-num/univer pull request #3959
Opened 2024-11-05 09:18 UTC by ybzky

close #3741 

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-11-06 00:32 UTC, wzhudev requested changes
Change in this PR should have test to cover. It seems that there are a lot of `if` conditions.

The title of this PR should be more specific.

2024-11-06 14:02 UTC, Jocs approved these changes

2024-11-06 14:04 UTC, Jocs commented on packages/sheets-numfmt-ui/src/controllers/__tests__/editor.controller.spec.ts
> +                                bl: 1,
prefer use `BooleanNumber.TRUE` ?

2024-11-07 01:57 UTC, wzhudev approved these changes

2024-11-07 08:02 UTC, merged