fix(sheet): cell render
dream-num/univer pull request #4032
Opened 2024-11-11 08:45 UTC by Dushusir

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-11-13 09:51 UTC, hexf00 approved these changes

2024-11-14 02:04 UTC, wzhudev reviewed
LGTM. Some usability details need to be addressed.

2024-11-14 02:04 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-worksheet.ts
> +        renderManagerService.getRenderById(unitId)?.with(SheetSkeletonManagerService).reCalculate();
这里如果没有发现对应的 renderer，抛出错误比较好，因为这个是给最终用户用的 API

2024-11-14 02:04 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-worksheet.ts
> +        renderManagerService.getRenderById(unitId)?.mainComponent?.makeDirty();
这里 `getRenderById()` 的结果应该缓存为局部变量

2024-11-14 02:04 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-sheet-hooks.ts
> +     * @returns
这里最好对 `@param` `@returns` 做一下具体描述

2024-11-14 02:06 UTC, wzhudev commented
I am marking this PR as verified because it only changes API.

2024-11-18 06:47 UTC, wzhudev approved these changes
LGTM

2024-11-18 06:47 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-worksheet.ts
> +            throw new Error('Render not found');
Please consider to expose more debug info in error messages. For example, `unitId`.

2024-11-18 08:24 UTC, hexf00 requested changes

2024-11-18 08:24 UTC, hexf00 commented on packages/sheets/src/index.ts
> +export { FSheetHooks } from './facade/f-sheet-hooks';
move to facade.ts

2024-11-18 08:25 UTC, hexf00 requested changes

2024-11-18 08:25 UTC, hexf00 commented on packages/sheets-ui/src/facade/f-sheet-hooks.ts
> +import { FSheetHooks, InterceptCellContentPriority, INTERCEPTOR_POINT, SheetInterceptorService } from '@univerjs/sheets';
import { FSheetHooks } from '@univerjs/sheets/facade';

2024-11-18 11:01 UTC, hexf00 approved these changes

2024-11-19 12:06 UTC, merged