refactor(sheets-ui): cell-editor & formula-editor
dream-num/univer pull request #4209
Opened 2024-12-02 14:26 UTC by weird94

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-12-03 02:56 UTC, wzhudev requested changes

2024-12-03 02:56 UTC, wzhudev commented on e2e/visual-comparison/sheets/sheets-visual-comparison.spec.ts-snapshots/default-sheet-fullpage-ci-chromium-linux.png
Why Undo & Redo buttons are activated when the application bootstraps? This does not meet our expectations.

2024-12-11 08:01 UTC, weird94 commented
https://github.com/dream-num/univer/pull/4209#issuecomment-2511698125

2024-12-28 06:33 UTC, weird94 commented
https://github.com/dream-num/univer/pull/4209#issuecomment-2511698125

2024-12-28 16:15 UTC, closed without merging