feat(formula): support lambda in function register
dream-num/univer pull request #4298
Opened 2024-12-13 10:27 UTC by Dushusir

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-12-31 05:12 UTC, wzhudev requested changes
The implementation looks good to me but we should add an example in the Facade API of regsitering functions.

2025-01-07 07:10 UTC, Dushusir commented
> The implementation looks good to me but we should add an example in the Facade API of regsitering functions.

Added exmaple here https://github.com/dream-num/univer/pull/4298/files#diff-2e2ce04086a2a743f70994698013f64bfe65b0df45577523d7c3eea046ce0202R61

2025-01-08 01:50 UTC, wzhudev approved these changes
LGTM

2025-01-08 01:50 UTC, wzhudev commented on packages/sheets-formula/src/facade/f-formula.ts
> +     * univerAPI.getFormula().registerFunction('CUSTOMSUM',(...variants) => {
```suggestion
     * univerAPI.getFormula().registerFunction('CUSTOMSUM', (...variants) => {
```

2025-01-10 03:11 UTC, merged