feat: user facade api
dream-num/univer pull request #4342
Opened 2024-12-20 07:46 UTC by lumixraku

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-12-20 12:07 UTC, weird94 approved these changes

2024-12-21 01:49 UTC, wzhudev requested changes

2024-12-21 01:49 UTC, wzhudev commented on packages/core/src/facade/f-univer.ts
> +        return this._injector.createInstance(FUser);
If the method's name is `getUserManager`, the Facade class should be `FUserManager` as well.

2024-12-21 01:49 UTC, wzhudev commented on packages/core/src/facade/f-user.ts
> +export class FUser extends FBase {
```suggestion
export class FUserManager extends FBase {
```

2024-12-21 01:49 UTC, wzhudev commented on packages/core/src/facade/f-user.ts
> +    getCurrUser(): IUser {
```suggestion
    getCurrentUser(): IUser {
```

Do not use abbreviation in Facade API. Choose the mose direct way to instruct our users.

2024-12-21 01:49 UTC, wzhudev commented on packages/sheets-thread-comment/src/facade/f-worksheet.ts
> +    onCommented(callback: (params: IAddCommentCommandParams) => void): IDisposable {
JSDoc required.

2024-12-21 01:49 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-workbook.ts
> +    onCellPointerDown(callback: (cell: IHoverRichTextInfo) => void): IDisposable {
JSDoc required.

2024-12-21 01:49 UTC, wzhudev commented on packages/sheets-ui/src/facade/f-workbook.ts
> +    onCellPointerDown(callback: (cell: IHoverRichTextInfo) => void): IDisposable {
These method should also be defined in the interface.

2024-12-23 02:46 UTC, wzhudev approved these changes
LGTM

2024-12-23 03:03 UTC, merged