feat: add paste options
dream-num/univer pull request #4393
Opened 2024-12-31 03:36 UTC by ybzky

close #xxx

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

2024-12-31 05:06 UTC, wzhudev requested changes

2024-12-31 05:06 UTC, wzhudev commented on packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
> +    const { sheetSkeletonManagerService } = useMemo(() => {
If it is not necessary, do not pass values in an object, which will give GC more jobs to do.

2024-12-31 05:06 UTC, wzhudev commented on packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
> +    const skeleton = sheetSkeletonManagerService?.getCurrentSkeleton();
This should reuse positioning logic with autofill. I assume that there is something you can leverage. cc @yuhongz @weird94

2024-12-31 05:06 UTC, wzhudev commented on packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
> +    const pasteOptionsCache = useObservable(clipboardService.pasteOptionsCache$, null);
Should provide an option to disable clipboard popup menu.

2024-12-31 06:08 UTC, yuhongz approved these changes
LGTM

2025-01-08 01:52 UTC, wzhudev approved these changes
LGTM

2025-01-08 01:55 UTC, merged