fix(sheet): appearance adjustment
dream-num/univer pull request #441
Opened 2023-11-12 09:31 UTC by DR-Univer

2023-11-12 13:02 UTC, Jocs approved these changes

2023-11-12 14:35 UTC, jikkai requested changes
3px 的 padding 不在规范内，如果组件需要使用一个脱离规范的数值时，可以考虑直接写死在组件里，不要追加新的 token

2023-11-13 01:33 UTC, wzhudev approved these changes

2023-11-13 01:33 UTC, wzhudev commented on packages/base-render/src/shape/scroll-bar.ts
> +    barBackgroundColor = 'rgba(255,255,255,0.5)';
Use theme color?

2023-11-13 02:26 UTC, DR-Univer commented on packages/base-render/src/shape/scroll-bar.ts
> +    barBackgroundColor = 'rgba(255,255,255,0.5)';
需要接入设计下，怎么把service引入到render里，这里我记个todo

2023-11-13 03:21 UTC, jikkai approved these changes

2023-11-13 03:23 UTC, merged