fix(sheet): sheet bar scroll button's state
dream-num/univer pull request #454
Opened 2023-11-15 03:27 UTC by Dushusir

2023-11-15 08:54 UTC, wzhudev requested changes

2023-11-15 08:54 UTC, wzhudev commented on packages/ui-plugin-sheets/src/commands/commands/rename.command.ts
> +            console.info('rename ===params', params);
Remove console.

2023-11-15 08:54 UTC, wzhudev commented on packages/ui-plugin-sheets/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
> +                    id: 'slideTabBarAlert',
Extract a const string here.

2023-11-16 02:22 UTC, Dushusir commented on packages/ui-plugin-sheets/src/commands/commands/rename.command.ts
> +            console.info('rename ===params', params);
> Remove console.
Embarrassed

2023-11-16 02:22 UTC, Dushusir commented on packages/ui-plugin-sheets/src/commands/commands/rename.command.ts
> +            console.info('rename ===params', params);
> Remove console.

Embarrassed

2023-11-16 07:07 UTC, wzhudev approved these changes

2023-11-16 07:07 UTC, merged