feat: delete right by delete key
dream-num/univer pull request #480
Opened 2023-11-17 13:05 UTC by Jocs

- [x] press Delete key to delete content at right of cursor

2023-11-18 00:54 UTC, wzhudev requested changes
关于 command 设计意图的问题需要讨论

2023-11-18 00:54 UTC, wzhudev commented on packages/base-docs/src/commands/commands/core-editing.command.ts
> +    handler: async () => true,
不太认同这里返回 true 然后通过命令监听在 controller 里面做的办法。handler 返回值应该告诉调用者命令是否执行成功，这样写背离了这个设计的初衷。

2023-11-18 00:54 UTC, wzhudev commented on packages/base-docs/src/controllers/delete-left-input.controller.ts
> +                    default:
这里跟 63 行的逻辑是重复的，不会进入到 default，感觉没必要写

2023-11-18 02:27 UTC, Jocs commented on packages/base-docs/src/commands/commands/core-editing.command.ts
> +    handler: async () => true,
最开始设想也应该是UI event 触发 controller，现在快捷键可以直接调用  controller 吗？

2023-11-18 02:29 UTC, Jocs commented on packages/base-docs/src/controllers/delete-left-input.controller.ts
> +                    default:
为啥是重复的呢？如果以后添加了监听的 command，但是没有写处理函数，就会走到 default，这样就会发现问题了。

2023-11-18 03:38 UTC, wzhudev commented on packages/base-docs/src/controllers/delete-left-input.controller.ts
> +                    default:
没生效一样能发现问题

2023-11-18 03:39 UTC, wzhudev commented on packages/base-docs/src/commands/commands/core-editing.command.ts
> +    handler: async () => true,
快捷键也在 controller 层，可以的，不要出现循环就可以了；

2023-11-18 04:01 UTC, Jocs commented on packages/base-docs/src/controllers/delete-left-input.controller.ts
> +                    default:
还是建议给 switch case 添加 default 语句，这样容易发现问题

2023-11-18 08:07 UTC, wzhudev commented on packages/base-docs/src/controllers/delete-left-input.controller.ts
> +                    default:
OK

2023-11-18 08:08 UTC, wzhudev commented
> > 关于 command 设计意图的问题需要讨论
> 
> 这儿就是把 command 作为一个事件通信了，现在菜单、快捷键好像挺多这样的用法

搜索了一下 () => true，好像都是你写的哎

2023-11-20 06:41 UTC, wzhudev approved these changes

2023-11-20 06:41 UTC, merged