sheet support freeze by row or column
dream-num/univer pull request #527
Opened 2023-11-22 15:15 UTC by weird94

#479 
1. 支持单独冻结行、列
2. 修复冻结ui在改变 单元格高度、自动高度 之后没有重绘的问题

2023-11-22 15:19 UTC, weird94 commented
![20231122231727_rec_](https://github.com/dream-num/univer/assets/16274199/d3f56672-6019-4a8e-97b3-fd157755ff00)

2023-11-23 00:49 UTC, wzhudev requested changes

2023-11-23 00:49 UTC, wzhudev commented on packages/ui-plugin-sheets/src/locale/en-US.ts
> +        freezeCol: 'Freeze column',
Freeze to this column

2023-11-23 00:49 UTC, wzhudev commented on packages/ui-plugin-sheets/src/controllers/freeze.controller.ts
> +            this._commandService.onCommandExecuted((command: ICommandInfo) => {
不用设置三个监听吧，在一个监听里对 command.id 做 switch 处理就好了

2023-11-23 00:49 UTC, wzhudev commented on packages/ui-plugin-sheets/src/commands/commands/set-frozen.command.ts
> +    handler: async (accessor) => {
command 均需要单元测试

2023-11-23 00:49 UTC, wzhudev commented on packages/ui-plugin-sheets/src/controllers/freeze.controller.ts
> +        console.log('===get position', position);
提交的代码请勿包含 console

2023-11-23 12:43 UTC, weird94 commented on packages/ui-plugin-sheets/src/controllers/freeze.controller.ts
> +            this._commandService.onCommandExecuted((command: ICommandInfo) => {
fixed

2023-11-23 14:01 UTC, wzhudev commented on packages/ui-plugin-sheets/src/controllers/freeze.controller.ts
> +                        (command.params as IDeltaRowHeightCommand).anchorRow < freeze.startRow
This should be `IDeltaColumnWidthCommand`?

2023-11-23 15:10 UTC, weird94 commented on packages/ui-plugin-sheets/src/commands/commands/set-frozen.command.ts
> +    handler: async (accessor) => {
done
see packages/ui-plugin-sheets/src/commands/commands/__tests__/set-frozen.command.spec.ts

2023-11-23 15:13 UTC, wzhudev approved these changes

2023-11-23 15:21 UTC, merged