feat(formula): paste with formula
dream-num/univer pull request #631
Opened 2023-12-04 12:46 UTC by Dushusir

- [x] paste with formula
- [x] auto sum edit cell 
- [x] force calculate formula when init

2023-12-04 14:07 UTC, yuhongz commented
LGTM

2023-12-05 01:42 UTC, wzhudev requested changes
有一些写法上的小问题。

另外请在合入后及时补充 formula-clipboard.controller 的单元测试

2023-12-05 01:42 UTC, wzhudev commented on packages/formula/src/controllers/utils.ts
> +    if (arrayFormulaRange == null || arrayFormulaRange[unitId] == null || arrayFormulaRange[unitId][sheetId] == null)
这里跟 46 行代码重复了，抽象一个函数出来

2023-12-05 01:42 UTC, wzhudev commented on packages/sheets-formula/src/commands/commands/formula-clipboard.command.ts
> +export const SheetPasteFormulaCommand: ICommand = {
这里应该是 仅粘贴公式 的意思吧？如果是的话，名字叫 `SheetOnlyPasteFormulaCommand` 吧，更加一目了然

2023-12-05 01:42 UTC, wzhudev commented on packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
> +                label: 'specialPaste.formula',
如果是特殊的常量，抽成一个全局的 const string

2023-12-05 01:42 UTC, wzhudev commented on packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
> +                const accessor = {
一个更方便的办法是通过 this._injector.invoke 方法调用一个函数

2023-12-05 12:03 UTC, DR-Univer approved these changes

2023-12-05 12:03 UTC, DR-Univer commented on packages/formula/src/controllers/trigger-calculation.controller.ts
> +            commands: [],
要传入强制计算forceCalculation:true

2023-12-05 13:09 UTC, wzhudev approved these changes

2023-12-05 13:09 UTC, merged