refactor(core): workbook insert sheet,remove sheet
dream-num/univer pull request #64
Opened 2023-08-25 09:58 UTC by Dushusir

2023-08-25 10:13 UTC, wzhudev requested changes
Some issues need to be addressed. But overall, it looks pretty good!

2023-08-25 10:13 UTC, wzhudev commented on packages/base-sheets/src/Basics/Interfaces/MutationInterface.ts
> +import { IWorksheetConfig } from '@univerjs/core';
这些 params 类型信息放在对应 mutation 的文件里就好了，以后会逐步清理掉这些专门放类型的 Interfaces/ Enums/ 目录

2023-08-25 10:13 UTC, wzhudev commented on packages/base-sheets/src/Commands/Mutations/insert-sheet.mutation.ts
> +            throw new Error(`Insert Sheet fail ${sheet.id} is already exist`);
Insert sheet fail ${sheet.id} already exists.

2023-08-25 10:13 UTC, wzhudev commented on packages/base-sheets/src/Commands/Mutations/insert-sheet.mutation.ts
> +        iSheets.set(sheet.id, new Worksheet(sheet, commandManager, observerManager, currentUniverService));
这里应该在 workbook 上暴露一个创建 worksheet 的方法，避免直接操作模块 workbook 内部的对象

2023-08-25 10:16 UTC, wzhudev commented on packages/ui-plugin-sheets/src/Controller/SheetBarUIContruller.ts
> +const mutationList = ['sheet.mutation.insert-sheet', 'sheet.mutation.remove-sheet'];
引用对应 mutation 的 id 属性，避免把字符串写两次

2023-08-28 02:45 UTC, Dushusir commented on packages/base-sheets/src/Basics/Interfaces/MutationInterface.ts
> +import { IWorksheetConfig } from '@univerjs/core';
![image](https://github.com/dream-num/univer/assets/26371161/b6d2471e-ceac-4abf-825f-ac654b671ad7)
这里RemoveSheet Undo返回用的是insert sheet的类型，如果放在对应 mutation 的文件会循环依赖。
如果放对应文件的话，是不是需要新定义一个IRemoveSheetUndoMutationParams 来避免循环?

2023-08-28 03:43 UTC, Dushusir commented on packages/ui-plugin-sheets/src/Controller/SheetBarUIContruller.ts
> +const mutationList = ['sheet.mutation.insert-sheet', 'sheet.mutation.remove-sheet'];
ui-plugin-sheets用到了base-sheets的src/Commands/Mutations, 用index.ts导出是否合理？

![image](https://github.com/dream-num/univer/assets/26371161/41cc3ee8-24b7-47e3-a9f7-e1b1db8a5ba1)

2023-08-28 11:25 UTC, wzhudev commented on packages/ui-plugin-sheets/src/Controller/SheetBarUIContruller.ts
> +const mutationList = ['sheet.mutation.insert-sheet', 'sheet.mutation.remove-sheet'];
不要在子目录里增加 index.ts 文件，全部从 plugin 顶层的 index.ts 导出

2023-08-29 06:27 UTC, wzhudev commented on packages/base-sheets/src/Basics/Interfaces/MutationInterface.ts
> +import { IWorksheetConfig } from '@univerjs/core';
Merge them into one file.

2023-08-29 10:07 UTC, wzhudev commented on packages/base-sheets/src/Commands/Mutations/remove-row-col.mutation.ts
> +export const IRemoveRowMutationFactory = (accessor: IAccessor, params: IRemoveRowMutationParams): IInsertRowMutationParams => {
注意命名规范，`I` 开头的只应该是接口

2023-08-29 10:08 UTC, wzhudev commented on packages/base-sheets/src/Commands/Mutations/remove-row-col.mutation.ts
> +export const IRemoveRowMutationFactory = (accessor: IAccessor, params: IRemoveRowMutationParams): IInsertRowMutationParams => {
而且这个是 undo factory，名字里没有 undo

2023-08-30 01:46 UTC, wzhudev commented
目前写的 command 需要能够处理上层没有传递 params 的情况，即能够按照当前 sheet 的选区的状态自动执行对应的任务 cc @eiji-th @JerryJiangZh @eiji-th

2023-08-31 06:58 UTC, merged