fix(sheet): freeze bugfix
dream-num/univer pull request #922
Opened 2023-12-27 16:30 UTC by weird94

- [ ] I am sure that the code is update-to-date with the `dev` branch.

close #890 
close #898

2023-12-28 01:59 UTC, Jocs commented on packages/sheets-ui/src/controllers/freeze.controller.ts
> +    private _activeViewport: Viewport | null = null;
Prefer `Nullable<Viewport>`

2023-12-28 01:59 UTC, Jocs commented on packages/sheets-ui/src/controllers/freeze.controller.ts
> +                activeViewport || undefined
`_getActiveViewport` 没有 activeViewport 直接返回 undefined，这儿就不用单独处理呢？

2023-12-28 02:53 UTC, weird94 commented on packages/sheets-ui/src/controllers/freeze.controller.ts
> +                activeViewport || undefined
是为了解决类型问题 _getActiveViewport可能返回null

2024-01-02 04:49 UTC, wzhudev requested changes
Should have unit test to cover changes.

2024-01-03 00:31 UTC, wzhudev approved these changes

2024-01-03 00:31 UTC, merged